Testing semantic
dayanyalfaro/cool-compiler-2020 pull request #10
Opened 2020-08-20 18:44 UTC by DalyPerez

close #7

2020-08-20 19:33 UTC, ginrod requested changes
removing outdate comments and testingprints

2020-08-20 19:33 UTC, ginrod commented on src/semantic_analyzer.py
> +                #TODO: falla xq no existen aun los tipos builtin
remove this

2020-08-20 19:38 UTC, ginrod requested changes
remove prints and comments

2020-08-20 19:38 UTC, ginrod commented on src/semantic_analyzer.py
> +            print(self.context.get_type(node.name))
remove this

2020-08-20 19:38 UTC, ginrod commented on src/semantic_analyzer.py
> +        self.current_type = self.context.get_type(node.name)  #TODO: creo que aqui debe ser node.name
remove comment

2020-08-20 19:38 UTC, ginrod commented on src/semantic_analyzer.py
> +        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
remove this

2020-08-20 19:38 UTC, ginrod commented on src/semantic_analyzer.py
> +        print(context)
remove this

2020-08-20 20:50 UTC, dayanyalfaro approved these changes

2020-08-21 00:56 UTC, ginrod approved these changes

2020-08-21 01:32 UTC, merged